package com.chance.mimorobot.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.chance.mimorobot.db.entity.FaceEntity;

import com.chance.mimorobot.db.dao.FaceEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig faceEntityDaoConfig;

    private final FaceEntityDao faceEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        faceEntityDaoConfig = daoConfigMap.get(FaceEntityDao.class).clone();
        faceEntityDaoConfig.initIdentityScope(type);

        faceEntityDao = new FaceEntityDao(faceEntityDaoConfig, this);

        registerDao(FaceEntity.class, faceEntityDao);
    }
    
    public void clear() {
        faceEntityDaoConfig.clearIdentityScope();
    }

    public FaceEntityDao getFaceEntityDao() {
        return faceEntityDao;
    }

}
